apps/pro/ui/config/routes.rb
                     as: 'activate'
    match 'offline_activation', action: :offline_activation,
                                as: 'offline_activation',
                                via: [:get, :post]
  end

  scope "hosts/:id" do
    get "new_loot" => "loots#new", :as => "new_loot"
    match "add_loot" => "loots#add_loot", :as => "add_loot", via: [:get, :post]
    get "" => "hosts#show", :as => "host"
    patch "" => "hosts#update", :as => "update_host"
    post "" => "hosts#create_or_update_tag"
    delete "" => "hosts#remove_tag", :as => "remove_tag"
    get "edit" => "hosts#edit", :as => "edit_host"
    get "services" => "hosts#services", :as => "host_services"
    get "sessions" => "hosts#sessions", :as => "host_sessions"
    get "vulns" => "hosts#vulns", :as => "host_vulns_tab"
    get "web_vulns" => "hosts#web_vulns", :as => "host_web_vulns_tab"
    get "shares" => "hosts#shares", :as => "host_shares"
    get "loots" => "hosts#loots", :as => "host_loots"
    get "notes" => "hosts#notes", :as => "host_notes"
    get "creds" => "hosts#creds", :as => "host_creds"
    get "tags" => "hosts#tags", :as => "host_tags"
    get "attempts" => "hosts#attempts", :as => "host_attempts"
    get "details" => "hosts#details", :as => "host_details"
    get "exploits" => "hosts#exploits", :as => "host_exploits"
    get "show_alive_sessions" => "hosts#show_alive_sessions", :as => "show_alive_sessions"
    get "show_dead_sessions" => "hosts#show_dead_sessions", :as => "show_dead_sessions"
    get "show_services/json" => "hosts#show_services", dataTable:false
    get "show_services" => "hosts#show_services", :as => "show_services", dataTable:true
    get "show_history" => "hosts#show_history", :as => "show_history"
    get "show_notes" => "hosts#show_notes", :as =>"show_notes"
    patch   "update_service" => "hosts#update_service", :as => "update_service"
    delete "delete_service" => "hosts#delete_service", :as => "delete_service"
    get "show_captured_data" => "hosts#show_captured_data", :as => "show_captured_data"
    put    "update_cred" => "hosts#update_cred", :as => "update_cred"
    delete "delete_cred" => "hosts#delete_cred", :as => "delete_cred"
    post   "create_service" => "hosts#create_service", :as => "create_service"
    post   "create_cred" => "hosts#create_cred", :as => "create_cred"
    post "poll_presenter" => "hosts#poll_presenter", :as => "poll_presenter"
    get  "poll_presenter" => "hosts#poll_presenter"
  end

  # Vulns
  scope "/hosts/:host_id", :as => "host" do
    resources :vulns

    namespace :metasploit do
      namespace :credential do
        resources :cores do
          collection do
            get :accessing,   action: :index, host_origin: :accessing
            get :originating, action: :index, host_origin: :originating
          end
        end

        resources :logins do
          collection do
            get :accessing, action: :index, host_origin: :accessing
          end
        end

      end
    end
  end

  # Listeners
  resources :listeners
  scope "/listener" do
    post ":id/stop" => "listeners#stop", :as => "listener_stop"
    post ":id/start" => "listeners#start", :as => "listener_start"
    get "module_options" => "listeners#module_options", :as => "macro_module_options"
  end
  delete "listeners" => "listeners#destroy", :as => "delete_listeners"

  # Backups
  scope "/backups" do
    get "new" => "backups#new", :as => "new_backup"
    post "create" => "backups#create", :as => "create_backup"
    post "restore" => "backups#restore", :as => "restore_backup"
    get "poll" => "backups#restore_poll", :as => "restore_poll"
    get "restart" => "backups#restart", :as => "backup_restart"
    post "status" => "backups#status", :as => "backup_restart_status"
    get "download" => "backups#download", :as => "download_backup"
    get "add" => "backups#add", :as => "add_backup"
    post "upload" => "backups#upload", :as => "upload_backup"
  end
  delete "backups" => "backups#destroy", :as => "delete_backups"

  get "login" => "user_sessions#new", :as => "login"
  post "logout" => "user_sessions#destroy", :as => "logout"

  # Mdm::Loot
  get "loot/:id" => "loots#get", :as => "loot"

  # Macros
  resources :macros
  scope "/macro" do
    delete ":id/delete_action/:action_id" => "macros#delete_action", :as => "macro_delete_action"
    delete ":id/delete_action" => "macros#delete_action", :as => "macro_delete_actions"
    post ":id/add_action" => "macros#add_action", :as => "macro_add_action"
    match "module_options" => "macros#module_options", :as => "module_options", via: [:get, :post]
  end
  delete "macros" => "macros#destroy", :as => "delete_macros"

  # NeXpose Consoles
  resources :nexpose_consoles do
    collection do
      delete "/destroy" => "nexpose_consoles#destroy", :as => "destroy"
    end
  end

  # Notifications
  namespace :notifications do
    resources :messages do
      collection do
        post 'mark_read' => 'messages#mark_read', :as => 'mark_read'
        get 'poll' => 'messages#poll', :as => 'poll'
      end
    end
  end

  # Payload information
  resources :payloads do
    collection do
      get :encoders
      get :formats
    end
  end

  namespace :rest_api do
    namespace :v1 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets

        resources :campaigns do
          resources :web_pages
          resources :emails
          resources :email_openings
          resources :phishing_results
          resources :visits
        end
      end
    end
    namespace :v2 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets
      end

      resources :workspaces, only: [:index, :show] do
        resources :campaigns, only: [:index, :show], controller: 'social_engineering/campaigns' do
          resources :web_pages, only: [:index, :show], controller: 'social_engineering/web_pages'
          resources :emails, only: [:index, :show], controller: 'social_engineering/emails'
          resources :email_openings, only: [:index, :show], controller: 'social_engineering/email_openings'
          resources :phishing_results, only: [:index, :show], controller: 'social_engineering/phishing_results'
          resources :visits, only: [:index, :show], controller: 'social_engineering/visits'
        end
        resources :hosts, only: [:index, :show] do
          resources :sessions, only: [:index, :show]
          resources :notes, only: [:index, :show]
          resources :services, only: [:index, :show] do
            resources :vulns, only: [:index, :show]
            resources :web_sites, only: [:index, :show] do
              resources :web_forms, only: [:index, :show]
              resources :web_pages, only: [:index, :show]
              resources :web_vulns, only: [:index, :show]
            end
          end
        end
      end
    end
  end

  # Sessions
  scope "sessions/:id" do
    delete "" => "sessions#destroy", :as => "delete_session"
    match "route" => "sessions#route", :as => "session_route", via: [:get, :post]
    get "vnc" => "sessions#vnc", :as => "session_vnc"
    match "shell" => "sessions#shell", :as => "session_shell", via: [:get, :post]
    get "files" => "sessions#files", :as => "session_files"
    get "search" => "sessions#search", :as => "session_search"
    post "upload" => "sessions#upload", :as => "session_upload"
    get "download" => "sessions#download", :as => "session_download"
    get "delete" => "sessions#delete", :as => "session_delete"
  end

  # Global Settings
  scope "/settings" do
    get "" => "settings#index", :as => "settings"
    patch "update_profile" => "settings#update_profile", :as => "update_profile"
    put "update_profile" => "settings#update_profile"
  end

  # Setup & Licenses
  scope "/setup" do
    get ""           => "licenses#setup", :as => "setup"
    get "request"    => "licenses#request_key", :as => "request_key"
    get "activation" => "licenses#activation", :as => "activation"
  end

  # Mdm::Tag Search
  get "tags" => "tags#search", :as => "search_tags"

  scope 'tasks', controller: :tasks do
    post 'stop', action: :stop,
                 as: 'stop_task'
    post 'stop_all', action: :stop_all,
                     as: 'stop_all_tasks'

    post ':workspace_id/stop', action: :stop_in_workspace,
                               as: 'stop_tasks_in_workspace'
    get 'replay/:id', action: :replay,
                      as: 'replay_task'

    scope ':id' do
      get 'logs',
          as: 'task_log',
          action: :logs
      post 'pause',
           as: 'pause_task',
           action: :pause
      post 'resume',
           as: 'resume_task',
           action: :resume
      post 'stop_paused',
           as: 'stop_paused_task',
           action: :stop_paused
    end
  end

  # Updates
  scope '/updates', controller: 'updates' do
    get  '',                   action: :updates,
                               as: 'updates'
    post 'check',              action: :check
    post 'apply',              action: :apply
    post 'restart',            action: :restart
    get  'status',             action: :status
    get  'offline_apply',      action: :offline_apply
    post 'offline_apply_post', action: :offline_apply_post,
                               as: 'updates_offline_apply_post'
  end

  resources :user_sessions

  # Mdm::User settings
  resources :users

  # Wizard related reporting routes
  get '/wizard_report_tab' => 'reports#form_for_tabbed_modal', :as => 'wizard_report_tab_form'

  # Wizards
  namespace :wizards do
    namespace :quick_pentest do
      resources :form
    end
    namespace :quick_web_app_scan do
      resources :form
    end
    namespace :vuln_validation do
      resources :form do
        collection do
          get  :nexpose_sites
          get  :import_run

apps/pro/ui/app/models/backup.rb
class Backup < Msf::Pro::MinimalBackup
  def self.generate(filename, description, overwrite: true, tee: nil, delay: false)
    archive = new(filename, overwrite: overwrite, tee: tee)
    if delay && archive.valid?
      archive.create_empty_zip(description)
      Backup.delay.generate(filename, description)
      archive
    elsif archive.errors.any?
      archive
    else
      if super
        backup_status = 'is complete'
      else
        backup_status = 'encountered an error'
      end

      Notifications::Message.create(
          title: 'Backup',
          content: "\"#{archive.name}\" #{backup_status}",
          url: '/settings#backups',
          kind: :system_notification
      )
    end
  end

  def self.restore_alternate(filepath, delay: false)
    archive = new(filepath)
    raise RuntimeError.new('Backup does not exist') unless archive.description
    raise RuntimeError.new('Backup is from a newer version of Metasploit') unless archive.compatible?

    archive.mark_restore_queued
    if delay
      Backup.delay.restore_alternate(filepath)
    else
      archive.restore_alternate
      Notifications::Message.create(
        title: "\"#{archive.name}\" restored",
        content: 'Please restart Metasploit.',
        url: '/settings#backups',
        kind: :system_notification
      )
    end

    archive
  end

  protected

  def self.rails_env
    Rails.env
  end
end

apps/pro/ui/app/controllers/backups_controller.rb
class BackupsController < ApplicationController
  protect_from_forgery except: :status
  skip_before_action :require_license, :only => [:status, :restart]
  skip_before_action :require_user, :only => [:status]
  before_action :require_admin, :except => [:status]

  def new
    render :action => 'new'
  end

  def create
    # Validate backup name
    if params[:name].length > 64
      @errors = { name_error: "Invalid length. Backup name cannot be more than 64 characters." }
      render :action => 'new', :status => :bad_request
    else
      archive = Backup.generate(params[:name], params[:description], overwrite: false, delay: true)
      if archive.errors.any?
        @errors = archive.errors
        render :action => 'new'
      else
        AuditLogger.admin "#{ip_user} - Backup started. name: #{params[:name]}, description: #{params[:description]}"
        redirect_to settings_path anchor: 'backups'
      end
    end   
  end

  def destroy
    params[:delete_backups].each do |backup|
      Backup.delete(backup)
      AuditLogger.admin "#{ip_user} - Backup deleted. name: #{backup}"
    end

    redirect_to settings_path anchor: 'backups'
  end

  def restore
    begin
      Backup.restore_alternate(params[:backup_name], delay: true)
      AuditLogger.admin "#{ip_user} - Backup restored. name: #{params[:backup_name]}"
      redirect_to restore_poll_path
    rescue RuntimeError => e
      flash[:error] = "\"#{params[:backup_name]}\" could not be restored: #{e}"
      redirect_to settings_path anchor: 'backups'
    end
  end

  def restore_poll
    @refresh = false
    @status = RestartStatus.get
    restore_job = Delayed::Job.where('handler LIKE \'%Backup%restore%\'').first
    if restore_job
      name = Psych.load_dj(restore_job.handler).args[0]
      @backup = Backup.new(name)
    end

    render :layout => 'static'
  end

  def restart
    @status = RestartStatus.get
    # if a backup is in progress wait to restart
    while Backup.running?
      sleep 0.4
    end
    success = @status.restart
    if not success
      flash[:error] = "Failed to restart"
    end
    redirect_to :action => :restore_poll
  end

  # XHR request
  def status
    name = params["backup"]
    @backup = Backup.new(name)
    @status = RestartStatus.get
    unless @status.restarting?
      if @backup.require_restart == true && !Backup.running?
        @backup.mark_restarted
        @status.restart
      end
    end
    render :partial => 'status'
  end

  def download
    backup = Backup.new(params[:backup_name])
    if backup.description.nil?
      flash[:error] = "\"#{params[:backup_name]}\" could not be downloaded: Backup does not exist"
      redirect_to settings_path anchor: 'backups'
    else
      send_file backup.zip_file
    end
  end

  def add
    render :action => 'add'
  end

  def upload
    # add upload code here, likely need to build a template view that may need to come from another endpoint
    error_msg = nil
    if params[:file_input].blank?
      error_msg = "No File Provided"
    else
      invalid_file_msg = "The file provided is not a valid backup."
      # write file to disk, validate file contents, consider if file contents can be validated from `tempfile` location
      upload_file = params[:file_input].tempfile

      if params[:file_input].content_type != 'application/zip'
        error_msg = flash[:error] = invalid_file_msg
      end
      # check for existing file
      existing_file = Backup.new(params[:file_input].original_filename)
      unless existing_file.ms_version.nil?
        error_msg = flash[:error] = invalid_file_msg
      else
        begin
          file_as_backup = Backup.new(upload_file, name_as_path: true, overwrite: false)
          if file_as_backup.ms_version.nil?
            error_msg = flash[:error] = invalid_file_msg
          end

          unless file_as_backup.compatible?
            error_msg = flash[:error] = "The file provided is not compatible with this version."
          else
            file = ::File.new(::File.join(Backup.locations.pro_backups_directory, params[:file_input].original_filename), "wb")
            file.write(upload_file.read)
            file.close
          end
        rescue JSON::ParserError => _e
          error_msg = flash[:error] = invalid_file_msg
        end
      end
    end

    if error_msg.present?
      flash[:error] = error_msg
      redirect_to :action => "add"
    else
      redirect_to settings_path anchor: 'backups'
    end
  end
end

apps/pro/ui/app/views/backups/_backups.html.erb
<div class="backups">

  <p>
    Backups can help prevent data loss and enable you to easily migrate data between Metasploit servers. A backup of Metasploit includes your application settings, all of your projects, and everything you need to restore your server to a specific state.
      <a href="https://help.rapid7.com/metasploit/#managing-updating-metasploit/back-up-restore.html" target="_blank">
        Learn more.
      </a>
  </p>

<%= form_tag restore_backup_path, :id => 'restore' %></form>

<%= form_tag delete_backups_path, :method => :delete do %>
  <div class="control-bar">
    <span class="button">
      <%= link_to "New Backup", new_backup_path, :class => "new" %>
    </span>
    <span class="button">
      <%= submit_tag "Delete", :class => "delete", :id => 'backup-delete-submit' %>
    </span>
    <span class="button">
      <%= link_to "Upload", add_backup_path, :class => "new" %>
    </span>
  </div>

  <table id="backup-list" class="list">
    <thead>
      <th class="checkbox"><%= check_box_tag "all-backups", true %></th>
      <th>File</th>
      <th>Description</th>
      <th>Date</th>
      <th>Metasploit Version</th>
      <th>Compressed Size</th>
      <th>Restored Size</th>
      <th>Status</th>
      <th>Restore</th>
    </thead>
    <tbody>
    <% if @backups %>
    <% @backups.each do |backup| %>
    <tr class="<%=h row_cycle %>">
      <td><%= check_box_tag("delete_backups[]", backup.name, false, :id => nil) %></td>
      <td class="backup-data">
        <% if backup.status =~ /Complete/i %>
          <%= link_to backup.name, download_backup_path(:backup_name => backup.name), :id => "#{backup.name.gsub(" ", "_")}_download" %>
        <% else%>
          <%=h backup.name %>
        <% end %>
      </td>
      <td class="backup-data">
        <%=h backup.description %>
      </td>
      <td class="backup-data">
        <%=h backup.date %>
      </td>
      <td class="backup-data">
        <%=h backup.ms_version_revision %>
      </td>
      <td>
        <%=h (backup.zip_size / (1024.0 * 1024.0)).round 2  %> MB
      </td>
      <td>
        <%=h (backup.size / (1024.0 * 1024.0)).round 2  %> MB
      </td>
      <td class="backup-status">
        <% if backup.status =~ /Complete/i %>
          <%=h backup.status %>
        <% else%>
          <%=h "Preparing" %>
        <% end %>
      </td>
      <% if backup.compatible? %>
        <td>
        <span class="btn">
          <%= submit_tag 'Restore', :type => 'button', :class => "restore", :form => 'restore', :data => {:backup_name => backup.name} %>
        </span>
        </td>
      <% else %>
        <td title="Backup version is newer than the current Metasploit release version. You cannot restore this backup.">
        <span class="btn disabled">
          <%= submit_tag 'Restore', :type => 'button', :class => "restore" %>
        </span>
        </td>
      <% end %>
    </tr>
    <% end %>
    <% else %>
      <td colspan=9 align=center>
        No Persistent Backups
      </td>
    <% end %>
    </tbody>
  </table>
<% end %>

</div>

<div id="restore-backup-confirmation" style="display: none;">
  <p>
    Restoring "<span id="backup-name"></span>" will overwrite everything in your database, including your user accounts, reports, logs, and loot. <br><br>Before you restore this backup, you should check if there are any tasks currently running. These tasks will be stopped during a restore and any data that you have not backed up will be lost. <br><br>The process may take a while to complete.
  </p>
</div>

<div id="delete-backup-confirmation" style="display: none;">
  <p>
    Deleting these backups will permanently remove them.
  </p>
  <table class="list">
    <thead>
      <th>File</th>
      <th>Description</th>
      <th>Date</th>
      <th>Metasploit Version</th>
    </thead>
    <tbody id="delete-backup-confirmation-list"></tbody>
  </table>
</div>

<%= nonced_javascript_tag do %>
  (function() {
    jQuery(function($) {
      $("#all-backups").checkAll($("#backup-list"));
    });
  }).call(this);
<% end %>

apps/pro/ui/app/views/backups/_fields.html.erb
<div class="one_col_without_sidebar">
  <div class="col1">

    <%= form_tag create_backup_path, class: "formtastic" do %>
      <%= render "shared/error_messages_general", :errors => @errors %>

      <fieldset class="inputs">
        <legend><span>Backup Information</span></legend>
          <ol>
            <li class="string input error required stringish">
              <%= label_tag :name, nil, class: 'label' do%>Name<abbr title="required">*</abbr>
              <% end %>
              <%= text_field_tag :name, '', size: 30, maxlength: 64 %>
              <% if @errors %>
                <p class="inline-errors"><%= @errors[:name_error] %></p>
              <% end %>
            </li>

            <li class="string input error required stringish">
              <%= label_tag :description, 'Description', class: 'label'%>
              <%= text_field_tag :description, '', size: 30, maxlength: 255 %>
              <% if @errors %>
                <p class="inline-errors"><%= @errors[:description_error] %></p>
              <% end %>
            </li>

            <li class="string input error required stringish">
              <%= label_tag :sumbit, ' ', class: 'label'%>
              <div class="buttons">
                <span class="btn"><%= submit_tag 'Create Backup', :class => "save" %></span>
              </div>
            </li>
          </ol>
      </fieldset>
    <% end %>
  </div>

</div>

apps/pro/ui/app/views/backups/_status.html.erb
<% if @backup.present? && @backup.status == '0/6: Queuing restore' %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="running">Queuing restore...</li>
      <li>Restore loots</li>
      <li>Restore reports</li>
      <li>Restore logs</li>
      <li>Restore tasks</li>
      <li>Restore the database</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /1\/6/ %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="running">Restoring loots...</li>
      <li>Restore reports</li>
      <li>Restore logs</li>
      <li>Restore tasks</li>
      <li>Restore the database</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /2\/6/ %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="running">Restoring reports...</li>
      <li>Restore logs</li>
      <li>Restore tasks</li>
      <li>Restore the database</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /3\/6/ %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="complete">Reports restored</li>
      <li class="running">Restoring logs...</li>
      <li>Restore tasks</li>
      <li>Restore the database</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /4\/6/ %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="complete">Reports restored</li>
      <li class="complete" class="complete">Logs restored</li>
      <li class="running">Restoring tasks...</li>
      <li>Restore the database</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /5\/6/ %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="complete">Reports restored</li>
      <li class="complete">Logs restored</li>
      <li class="complete">Tasks restored</li>
      <li class="running">Restoring the database...</li>
      <li>Restart Metasploit</li>
    </ol>
<% elsif @backup.present? && @backup.status =~ /complete/i && @status.restarting? %>
    <p class="justify"><b>We are restoring your backup. This can take a while, we appreciate your patience.</b></p>
    <p><i>Need something to do while you're waiting? Check out our Whiteboard Wednesday videos. Every week we tackle timely security events and topics that we think are important to you.</i>
      <br/><br/><a href="http://www.rapid7.com/resources/videos/" target="_blank">http://www.rapid7.com/resources/videos/</a></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="complete">Reports restored</li>
      <li class="complete">Logs restored</li>
      <li class="complete">Tasks restored</li>
      <li class="complete">Database restored</li>
      <li class="running">Waiting for services to restart...</li>
    </ol>
<% elsif @status.error? %>
    <p>
      Restarting Failed: <%= h @status.error %>
    </p>
    <span class="btn">
      <%= link_to "Back to Projects List", root_path, :class => "back" %>
	</span>
<% else %>
    <p class="justify"><b>Your backup has been restored.</b></p>
    <ol>
      <li class="complete">Restore queued</li>
      <li class="complete">Loots restored</li>
      <li class="complete">Reports restored</li>
      <li class="complete">Logs restored</li>
      <li class="complete">Tasks restored</li>
      <li class="complete">Database restored</li>
      <li class="complete">Restore Complete</li>
    </ol>
    <span class="btn">
      <%= link_to "Back to Projects List", root_path, :class => "back" %>
    </span>
<% end %>

apps/pro/ui/app/views/backups/_upload_fields.html.erb
<div class="one_col_without_sidebar">
  <div class="col1">

    <%= form_tag upload_backup_path, class: "formtastic", :multipart => true do  %>
      <%= render "shared/error_messages_general", :errors => @errors %>

      <fieldset>
        <legend><span>Upload Backup File</span></legend>
          <ol>

            <li class="string input error required stringish">
              <%= label_tag :file_input, 'File to Upload' %>
              <%= file_field_tag :file_input, :size => 80, :autofocus => true, :accept => 'application/zip' %>
            </li>

            <li>
              <div class="buttons">
                <%= label_tag :submit, ' ', class: 'label'%>
                <span class="btn"><%= submit_tag "Upload", :class => "save" %></span>
              </div>
            </li>
        </ol>
      </fieldset>
    <% end %>
  </div>

</div>

apps/pro/ui/app/views/backups/add.html.erb
<% title "Backup - Upload" %>
<% breadcrumb link_to("Global Settings", settings_path), link_to("Backups", settings_path(anchor: 'backups')), link_to("Upload", add_backup_path) %>

<% content_for :header_buttons do %>
	<span class="btn">
		<%= link_to "Back to Backups", settings_path(anchor: 'backups'), :class => "back" %>
	</span>
<% end %>

<%= render 'upload_fields' %>

apps/pro/ui/app/views/backups/new.html.erb
<% title "Backup - Create" %>
<% breadcrumb link_to("Global Settings", settings_path), link_to("Backups", settings_path(anchor: 'backups')), link_to("Create", new_backup_path) %>

<% content_for :header_buttons do %>
	<span class="btn">
		<%= link_to "Back to Backups", settings_path(anchor: 'backups'), :class => "back" %>
	</span>
<% end %>

<%= render 'fields' %>

apps/pro/ui/app/views/backups/restore_poll.html.erb
<% include_jquery_ui %>
<head>
  <%= yield :jquery %>
  <%= javascript_include_tag 'restore' %>
  <% if @backup.present? %>
    <meta name="msp:backup_present" content="true" />
    <meta name="msp:backup_name" content="<%= @backup.name %>" />
  <% end %>
</head>
<% title 'Metasploit restore status' %>

<div id="restart_status">
  <%= render :partial => 'status' %>
</div>
<div id="error" style="display:none">
</div>