apps/pro/ui/config/routes.rb
    delete ":id/delete_action/:action_id" => "macros#delete_action", :as => "macro_delete_action"
    delete ":id/delete_action" => "macros#delete_action", :as => "macro_delete_actions"
    post ":id/add_action" => "macros#add_action", :as => "macro_add_action"
    match "module_options" => "macros#module_options", :as => "module_options", via: [:get, :post]
  end
  delete "macros" => "macros#destroy", :as => "delete_macros"

  # NeXpose Consoles
  resources :nexpose_consoles do
    collection do
      delete "/destroy" => "nexpose_consoles#destroy", :as => "destroy"
    end
  end

  # Notifications
  namespace :notifications do
    resources :messages do
      collection do
        post 'mark_read' => 'messages#mark_read', :as => 'mark_read'
        get 'poll' => 'messages#poll', :as => 'poll'
      end
    end
  end

  # Payload information
  resources :payloads do
    collection do
      get :encoders
      get :formats
    end
  end

  namespace :rest_api do
    namespace :v1 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets

        resources :campaigns do
          resources :web_pages
          resources :emails
          resources :email_openings
          resources :phishing_results
          resources :visits
        end
      end
    end
    namespace :v2 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets
      end

      resources :workspaces, only: [:index, :show] do
        resources :campaigns, only: [:index, :show], controller: 'social_engineering/campaigns' do
          resources :web_pages, only: [:index, :show], controller: 'social_engineering/web_pages'
          resources :emails, only: [:index, :show], controller: 'social_engineering/emails'
          resources :email_openings, only: [:index, :show], controller: 'social_engineering/email_openings'
          resources :phishing_results, only: [:index, :show], controller: 'social_engineering/phishing_results'
          resources :visits, only: [:index, :show], controller: 'social_engineering/visits'
        end
        resources :hosts, only: [:index, :show] do
          resources :sessions, only: [:index, :show]
          resources :notes, only: [:index, :show]
          resources :services, only: [:index, :show] do
            resources :vulns, only: [:index, :show]
            resources :web_sites, only: [:index, :show] do
              resources :web_forms, only: [:index, :show]
              resources :web_pages, only: [:index, :show]
              resources :web_vulns, only: [:index, :show]
            end
          end
        end
      end
    end
  end

  # Sessions
  scope "sessions/:id" do
    delete "" => "sessions#destroy", :as => "delete_session"
    match "route" => "sessions#route", :as => "session_route", via: [:get, :post]
    get "vnc" => "sessions#vnc", :as => "session_vnc"
    match "shell" => "sessions#shell", :as => "session_shell", via: [:get, :post]
    get "files" => "sessions#files", :as => "session_files"
    get "search" => "sessions#search", :as => "session_search"
    post "upload" => "sessions#upload", :as => "session_upload"
    get "download" => "sessions#download", :as => "session_download"
    get "delete" => "sessions#delete", :as => "session_delete"
  end

  # Global Settings
  scope "/settings" do
    get "" => "settings#index", :as => "settings"
    patch "update_profile" => "settings#update_profile", :as => "update_profile"
    put "update_profile" => "settings#update_profile"
  end

  # Setup & Licenses
  scope "/setup" do
    get ""           => "licenses#setup", :as => "setup"
    get "request"    => "licenses#request_key", :as => "request_key"
    get "activation" => "licenses#activation", :as => "activation"
  end

  # Mdm::Tag Search
  get "tags" => "tags#search", :as => "search_tags"

  scope 'tasks', controller: :tasks do
    post 'stop', action: :stop,
                 as: 'stop_task'
    post 'stop_all', action: :stop_all,
                     as: 'stop_all_tasks'

    post ':workspace_id/stop', action: :stop_in_workspace,
                               as: 'stop_tasks_in_workspace'
    get 'replay/:id', action: :replay,
                      as: 'replay_task'

    scope ':id' do
      get 'logs',
          as: 'task_log',
          action: :logs
      post 'pause',
           as: 'pause_task',
           action: :pause
      post 'resume',
           as: 'resume_task',
           action: :resume
      post 'stop_paused',
           as: 'stop_paused_task',
           action: :stop_paused
    end
  end

  # Updates
  scope '/updates', controller: 'updates' do
    get  '',                   action: :updates,
                               as: 'updates'
    post 'check',              action: :check
    post 'apply',              action: :apply
    post 'restart',            action: :restart
    get  'status',             action: :status
    get  'offline_apply',      action: :offline_apply
    post 'offline_apply_post', action: :offline_apply_post,
                               as: 'updates_offline_apply_post'
  end

  resources :user_sessions

  # Mdm::User settings
  resources :users

  # Wizard related reporting routes
  get '/wizard_report_tab' => 'reports#form_for_tabbed_modal', :as => 'wizard_report_tab_form'

  # Wizards
  namespace :wizards do
    namespace :quick_pentest do
      resources :form
    end
    namespace :quick_web_app_scan do
      resources :form
    end
    namespace :vuln_validation do
      resources :form do
        collection do
          get  :nexpose_sites
          get  :import_run
          post :continue_exploitation
        end
      end
    end
    namespace :payload_generator do
      resources :form do
        collection do
          get :poll
          get :download
          get :upsell
        end
      end
    end
  end

  # Workspace
  # @todo Fix mispelling of 'workspaces'
  scope 'workspace/:workspace_id' do
    delete 'events',
           to: 'events#delete_all'
    get 'tasks/update_cred_file',
        as: nil,
        to: 'tasks#update_cred_file'
  end

  #
  # Workspaces
  #

  get "/workspaces/search" => "workspaces#search"
  delete "/workspaces/destroy" => "workspaces#destroy"

  resources :workspaces do
    namespace :apps do
      resources :app_runs, as: :runs do
        member do
          put :abort
        end
      end

      resources :apps

      namespace :credential_intrusion do
        resources :task_config
      end

      # prevent the double "apps" in: /workspace/1/apps/apps/overview
      get 'overview',
          as: 'overview',
          to: 'apps#overview'

      namespace :pass_the_hash do
        resources :task_config do
          get 'show_smb_hashes', on: :collection
        end
      end

      namespace :passive_network_discovery do
        resources :task_config
      end

      namespace :single_password do
        resources :task_config do
          get 'show_creds', on: :collection
        end
      end

      namespace :ssh_key do
        resources :task_config do
          get 'show_ssh_keys', on: :collection
        end
      end
    end

    namespace :brute_force do
      scope module: 'guess' do
        resources :guess
      end

      namespace :guess do
        resources :runs, only: [:create] do
          collection do
            post :target_count
          end
        end
      end

      namespace :reuse do
        resources :groups do
          member do
            get :cores
          end
        end

        resources :targets do
          collection do
            get :filter_values
            get :search_operators
          end

          member do
            get :index
          end
        end
      end

      resources :runs
    end

    get 'credentials' => 'metasploit/credential/cores#index', :as => 'credentials'

    resources :creds, only: [:index]
    resources :custom_reports, controller: :reports

    resources :events, only: [:index]

    resources :exports do
      collection do
        delete :destroy_multiple
      end

      member do
        get 'download' => 'exports#download'
      end
    end

    namespace :fuzzing do
      resources :fuzzing do
        resources :request_groups
      end
    end

    resources :imports, only: [:new]

    resources :loots, only: [:index, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end

    namespace :metasploit do
      namespace :credential do
        root to: 'cores#index'

        resources :cores do
          collection do
            delete :destroy_multiple
            get    :export
            get    :filter_values
            post   :quick_multi_tag
            get    :search_operators
          end

          member do
            put :remove_tag
            get :tags
          end

          resources :logins do
            collection do
              delete :destroy_multiple
              post :quick_multi_tag
            end

            member do
              post :get_session
              put :remove_tag
              get :tags
              post :validate_authentication
            end
          end

          resource  :origin, only: [:show]
        end

        resources :logins do
          member do
            post :attempt_session
            get  :get_session
            post :validate_authentication
          end
        end
      end
    end

    resources :module_details, only: [:show]

    namespace :nexpose do
      namespace :data do
        resources :import_runs, only: [:create,:show]

        resources :sites, only: [:index] do
          collection do
            get :filter_values
            get :search_operators
          end
        end
      end

      namespace :result do
        resources :exceptions, only: [:create,:show]
        resources :export_runs, only: [:create]

apps/pro/ui/app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_action :require_admin

  @@submitted_profile = nil

  def index
    @macros    = Mdm::Macro.all
    @api_keys  = Mdm::ApiKey.all
    @listeners = Mdm::Listener.all
    @consoles  = Mdm::NexposeConsole.all
    @backups   = Backup.all.sort_by(&:date)
    @profile   = @@submitted_profile.nil? ? current_profile : @@submitted_profile
    @@submitted_profile = nil
  end


  def update_profile
    pid = params[:profile_id]
    params[:smtp_ssl] = true if params[:smtp_ssl] == "true"

    @profile = Mdm::Profile.find(pid)
    current = @profile.settings.dup

    if @profile.blank?
      flash[:error] = "Invalid Mdm::Profile ID"
      redirect_to :action => 'index'
    end

    @profile.settings_list.each do |s|
      key = s[:name].intern
      val = params[key]

      next if val.nil?

      if s[:type] == :boolean
        val = (val.to_s =~ /(true|1|yes)/) ? true : false
      end
      @profile.settings[s[:name]] = val
    end

    if smtp_settings_present?
      update_smtp_settings
      unless smtp_settings_valid?
        @@submitted_profile = @profile
        # this relies on that smtp setting are on a unique page
        # allowing error set by side-effect to be returned
        return redirect_to :action => 'index', :anchor => params[:anchor]
      end
    end
    update_ui_settings if ui_settings_present?
    update_proxy_settings
    @profile.save!
    UsageMetrics.update_config
    updated = @profile.settings

    Mdm::Profile.record_timestamps = false
    @profile.update :updated_at => Time.now.utc
    Mdm::Profile.record_timestamps = true

    @profile.load_smtp_configuration

    flash[:notice] = "Settings successfully updated."
    AuditLogger.settings "#{ip_user} - Settings updated. #{audit_view(current, updated)}"

    redirect_to :action => 'index', :anchor => params[:anchor]
  end

  private

  # Ensure that SMTP information is complete if provided.
  # @return [Boolean]
  def smtp_settings_valid?
    status, error_msg = check_smtp_settings

    if status == :error
      flash[:error] = "SMTP Settings Error: #{error_msg}"
      false
    else
      true
    end
  end

  # Assume the user wants to use an SMTP server if they have anything in the address field
  # @return [Boolean]
  def smtp_settings_present?
    params[:smtp_address].present?
  end

  # Assume the user is updating server settings if `logged_in_timeout` is present
  # @return [Boolean]
  def ui_settings_present?
    params[:ui_server_logged_in_timeout].present?
  end

  def update_ui_settings
    ui_server_params = ui_server_allowed_params
    UIServerSettings.new(ui_server_params).apply_to(@profile.settings)
  end

  def update_proxy_settings
    if params['use_http_proxy'].present?
      Mdm::Profile::HTTP_PROXY_SETTINGS.each do |setting|
        @profile.settings[setting.to_s] = params[setting]
      end
    end
  end

  def update_smtp_settings
    smtp_params = smtp_allowed_params
    SmtpSettings.new(smtp_params).apply_to(@profile.settings)
  end

  # Perform a check of the provided SMTP information to ensure that the server
  # is up and responds to the settings.
  def check_smtp_settings
    smtp_params = smtp_allowed_params
    use_ssl = smtp_params[:smtp_ssl]
    server = smtp_params[:smtp_address]
    port = smtp_params[:smtp_port].to_i
    username = smtp_params[:smtp_username]
    password = smtp_params[:smtp_password]
    domain = smtp_params[:smtp_domain]
    auth = smtp_params[:smtp_authentication]
    if password == SmtpSettings::PASSWORD_UNCHANGED
      password = @profile.settings['smtp_password']
    end
    settings_validator = SmtpSettingsValidator.new(
        :server => server,
        :port => port,
        :ssl => use_ssl,
        :domain => domain,
        :username => username,
        :password => password,
        :auth => auth)
    valid = settings_validator.valid?
    error_msg = settings_validator.errors.join(', ')
    status = valid ? :ok : :error
    [status, error_msg]
  end

  def audit_view(current, updated)
    AuditHelper.compare(current, updated, filter: Mdm::Profile::PASSWORD_SETTINGS, same: false)
  end

  def ui_server_allowed_params
    params.slice(:ui_server_logged_in_timeout, :ui_server_consecutive_failed_logins_limit).permit!
  end

  def smtp_allowed_params
    params.slice(:smtp_ssl, :smtp_address, :smtp_port, :smtp_username, :smtp_password, :smtp_domain, :smtp_authentication).permit!
  end
end

apps/pro/ui/app/helpers/settings_helper.rb
module SettingsHelper
end

apps/pro/ui/app/views/settings/_profile.html.erb
<% include_javascript 'settings/_profile' %>

<div class="profile_settings">

  <%= form_tag update_profile_path, :method => :patch do %>

  <%= hidden_field_tag 'profile_id', @profile.id %>
  <%= hidden_field_tag 'anchor', 'global_settings' %>

    <table id="profile_settings_list" class="list">
      <thead>
        <th>Value</th>
        <th>Category</th>
        <th>Setting</th>
        <th>Description</th>
      </thead>
      <tbody>

      <% @profile.settings_list.each do |s|
        val = @profile.settings.has_key?(s[:name]) ? @profile.settings[s[:name]] : s[:default]
      %>
      <% if License.get.supports_global?(s[:name]) %>
      <tr class="<%=h row_cycle %>">
        <td width="20">
          <%  case s[:type]
            when :boolean
                  # Ensure possibility of toggling setting state. See http://apidock.com/rails/ActionView/Helpers/FormHelper/check_box %>
              <%= hidden_field_tag h(s[:name]), 0 %>
              <%= check_box_tag h(s[:name]), true, val %>
            <%
            when :text
            %>
              <%= text_field_tag h(s[:name]), true, h(val) %>
            <%
            end
          %>
        </td>
        <td width="20">
          <b><%= s[:category] %></b>
        </td>
        <td width="30">
          <b><%=h s[:name] %></b>
        </td>
        <td>
          <%=h s[:desc] %>
        </td>
      </tr>
      <% end %>
      <% end %>

      </tbody>
    </table>

    <div class="proxy_settings">
      <div id="proxy_fields" style="<%= display_none_if !@profile.settings["use_http_proxy"] %>" class="inline_fields">
        <h3>HTTP Proxy Settings</h3>
        <p>
          <%= label_tag :http_proxy_host, "Proxy IP" %>
          <%= text_field_tag :http_proxy_host, @profile.settings["http_proxy_host"] %>
        </p>

        <p>
          <%= label_tag :http_proxy_port, "Port" %>
          <%= text_field_tag :http_proxy_port, @profile.settings["http_proxy_port"], :size => 5 %>
        </p>

        <p>
          <%= label_tag :http_proxy_user, "Username" %>
          <%= text_field_tag :http_proxy_user, @profile.settings["http_proxy_user"], :autocomplete => "off" %>
        </p>

        <p>
          <%= label_tag :http_proxy_pass, "Password" %>
          <%= password_field_tag :http_proxy_pass, @profile.settings["http_proxy_pass"], :autocomplete => "off" %>
        </p>
      </div>
    </div>
    <br />
    <div class="buttons">
      <span class="btn"><%= submit_tag 'Update Settings', :method => :patch, :class => "save" %></span>
    </div>

  <% end %>

  <% nonced_javascript_tag do %>
    (function() {
      jQuery(function($) {
        $("#use_proxy").toggleVisibility($("#proxy_fields"));
      });
    }).call(this);
  <% end %>

</div>

apps/pro/ui/app/views/settings/_smtp.html.erb
<% smtp = @profile.smtp_settings %>
<div class="smtp_settings">
  <h2></h2>

  <%= form_tag update_profile_path, :method => :put do %>
    <%= hidden_field_tag 'profile_id', @profile.id %>
    <%= hidden_field_tag 'anchor', 'smtp_settings' %>
    <div id="smtp_fields" class="inline_fields">      
      <p>
        <%= label_tag :smtp_address, "Address" %>
        <%= text_field_tag :smtp_address, smtp.address %>
      </p>
      <p>
        <%= label_tag :smtp_port, "Port" %>
        <%= number_field_tag :smtp_port, smtp.port, :within => 1...65536, :maxlength => 5, :size => 5, :required => true %>
      </p>
      <p>
        <%= label_tag :smtp_ssl, "Use SSL?" %>
        <%= check_box_tag :smtp_ssl, true, smtp.ssl%>
      <p>
        <%= label_tag :smtp_domain, "Domain" %>
        <%= text_field_tag :smtp_domain, smtp.domain %>
      </p>
      <p>
        <%= label_tag :smtp_username, "Username" %>
        <%= text_field_tag :smtp_username, smtp.username, :autocomplete => "off" %>
      </p>
      <p>
        <%= label_tag :smtp_password, "Password" %>
                <% safe_password = nil

                   unless smtp.password.blank?
                     safe_password = SmtpSettings::PASSWORD_UNCHANGED
                   end %>
        <%= password_field_tag :smtp_password, safe_password, :autocomplete => "off" %>
      </p>
      <p>
        <%= label_tag :smtp_authentication, "Authentication" %>
        <%= select_tag :smtp_authentication, 
            options_for_select(['plain', 'login', 'cram_md5'], smtp.authentication) %>
      </p>
    </div>
    <br />
    <div class="buttons">
      <span class="btn"><%= submit_tag 'Update Settings', :method => :put, :class => "save" %></span>
    </div>
  <% end %>
</div>

apps/pro/ui/app/views/settings/_web_server.html.erb
<% ui_server = @profile.ui_server_settings %>
<% title "Web Server Settings" %>
<div class="web_server">
  <h2></h2>

  <%= form_tag update_profile_path, :method => :put do %>
    <%= hidden_field_tag 'profile_id', @profile.id %>
    <%= hidden_field_tag 'anchor', 'web_server' %>
    <p>
      Metasploit Pro contains an embedded web server. The following web server settings can be configured. Changes to these setting require restart of services to apply.
    </p>
    <div id="web_server_fields" class="wide_inline_fields">
      <p>
        <%= label_tag :ui_server_logged_in_timeout, "Session timeout (seconds)" %>
        <%= number_field_tag :ui_server_logged_in_timeout, ui_server.logged_in_timeout, :within => 0...259200, :maxlength => 6, :size => 6, :required => true %>
      </p>
      <p>
        <%= label_tag :ui_server_consecutive_failed_logins_limit, "Failed login threshold" %>
        <%= number_field_tag :ui_server_consecutive_failed_logins_limit, ui_server.consecutive_failed_logins_limit, :within => 0...500, :maxlength => 3, :size => 3, :required => true %>
      </p>
    </div>
    <br />
    <div class="buttons">
      <span class="btn"><%= submit_tag 'Update Settings', :method => :put, :class => "save" %></span>
    </div>
  <% end %>
</div>

apps/pro/ui/app/views/settings/index.html.erb
<% title "Global Settings" %>
<% breadcrumb link_to("Global Settings", settings_path) %>
<% include_stylesheet 'settings/index' -%>
<% include_javascript "api_keys/_index" %>
<% include_javascript "macros" %>
<% include_javascript "nexpose_consoles/_index" %>
<% include_javascript "listeners/_index" %>
<% include_javascript "settings/_index" %>
<% include_javascript "backups/_index" %>

<ul class='tabs'>
  <li class='tab'><a class='active' href='javascript:void(0)'>Global Settings</a></li>

  <li class='tab'><a href='javascript:void(0)'>SMTP Settings</a></li>

  <% if License.get.supports_api? %>
    <li class='tab'><a href='javascript:void(0)'>API Keys</a></li>
  <% end %>

  <% if License.get.supports_macros? %>
    <li class='tab'><a href='javascript:void(0)'>Post-Exploitation Macros</a></li>
  <% end %>

  <% if License.get.supports_listeners? %>
    <li class='tab'><a href='javascript:void(0)'>Persistent Listeners</a></li>
  <% end %>

  <li class='tab'><a href='javascript:void(0)'>Nexpose Consoles</a></li>

  <% if current_user.admin %>
    <li class='tab'><a href='javascript:void(0)'>Stop All Tasks</a></li>
    <li class='tab'><a href='javascript:void(0)'>Backups</a></li>
    <li class='tab'><a href='javascript:void(0)'>Web Server</a></li>
  <% end %>
</ul>

<style type='text/css'>
div.tabs>div {
  margin-top: 18px;
}
</style>

<div class='tabs'>
  <div id="profile_container">
    <%= render "profile", :profile => @profile %>
  </div>

  <div id="smtp_container">
    <%= render "smtp", :profile => @profile %>
  </div>

  <% if License.get.supports_api? %>
    <div id="api_keys_container">
      <%= render "api_keys/api_keys", :apikeys => @api_keys %>
    </div>
  <% end %>

  <% if License.get.supports_macros? %>
    <div id="macros_container">
      <%= render "macros/macros", :macros => @macros %>
    </div>
  <% end %>

  <% if License.get.supports_listeners? %>
    <div id="listeners_container">
      <%= render "listeners/listeners", :listeners => @listeners %>
    </div>
  <% end %>

  <div id="consoles_container">
    <%= render "nexpose_consoles/nexpose_consoles", :consoles => @consoles %>
  </div>

  <% if current_user.admin %>
    <div id="stop-all-tasks">
      <h2 style="color:red">Stop all tasks in all projects</h2>
      <p>
        <strong>This will stop every single running task in the application. Be VERY sure you want to do this!</strong>
      </p>
      <span class="btn">
      <%= link_to 'Stop all tasks', stop_all_tasks_path, :data => { :confirm => 'Immediately stop all tasks in the application? There is no undo!', :method => :post, :remote => true}, :class => 'cancel', :title => "Stop all tasks" %>
      </span>
    </div>

    <div id="backups_container">
      <%= render "backups/backups", :backups => @backups %>
    </div>

    <div id="web_server_settings">
      <%= render "web_server", :ui_server => @ui_server %>
    </div>
  <% end %>
</div>