apps/pro/ui/config/routes.rb
    get  '',                   action: :updates,
                               as: 'updates'
    post 'check',              action: :check
    post 'apply',              action: :apply
    post 'restart',            action: :restart
    get  'status',             action: :status
    get  'offline_apply',      action: :offline_apply
    post 'offline_apply_post', action: :offline_apply_post,
                               as: 'updates_offline_apply_post'
  end

  resources :user_sessions

  # Mdm::User settings
  resources :users

  # Wizard related reporting routes
  get '/wizard_report_tab' => 'reports#form_for_tabbed_modal', :as => 'wizard_report_tab_form'

  # Wizards
  namespace :wizards do
    namespace :quick_pentest do
      resources :form
    end
    namespace :quick_web_app_scan do
      resources :form
    end
    namespace :vuln_validation do
      resources :form do
        collection do
          get  :nexpose_sites
          get  :import_run
          post :continue_exploitation
        end
      end
    end
    namespace :payload_generator do
      resources :form do
        collection do
          get :poll
          get :download
          get :upsell
        end
      end
    end
  end

  # Workspace
  # @todo Fix mispelling of 'workspaces'
  scope 'workspace/:workspace_id' do
    delete 'events',
           to: 'events#delete_all'
    get 'tasks/update_cred_file',
        as: nil,
        to: 'tasks#update_cred_file'
  end

  #
  # Workspaces
  #

  get "/workspaces/search" => "workspaces#search"
  delete "/workspaces/destroy" => "workspaces#destroy"

  resources :workspaces do
    namespace :apps do
      resources :app_runs, as: :runs do
        member do
          put :abort
        end
      end

      resources :apps

      namespace :credential_intrusion do
        resources :task_config
      end

      # prevent the double "apps" in: /workspace/1/apps/apps/overview
      get 'overview',
          as: 'overview',
          to: 'apps#overview'

      namespace :pass_the_hash do
        resources :task_config do
          get 'show_smb_hashes', on: :collection
        end
      end

      namespace :passive_network_discovery do
        resources :task_config
      end

      namespace :single_password do
        resources :task_config do
          get 'show_creds', on: :collection
        end
      end

      namespace :ssh_key do
        resources :task_config do
          get 'show_ssh_keys', on: :collection
        end
      end
    end

    namespace :brute_force do
      scope module: 'guess' do
        resources :guess
      end

      namespace :guess do
        resources :runs, only: [:create] do
          collection do
            post :target_count
          end
        end
      end

      namespace :reuse do
        resources :groups do
          member do
            get :cores
          end
        end

        resources :targets do
          collection do
            get :filter_values
            get :search_operators
          end

          member do
            get :index
          end
        end
      end

      resources :runs
    end

    get 'credentials' => 'metasploit/credential/cores#index', :as => 'credentials'

    resources :creds, only: [:index]
    resources :custom_reports, controller: :reports

    resources :events, only: [:index]

    resources :exports do
      collection do
        delete :destroy_multiple
      end

      member do
        get 'download' => 'exports#download'
      end
    end

    namespace :fuzzing do
      resources :fuzzing do
        resources :request_groups
      end
    end

    resources :imports, only: [:new]

    resources :loots, only: [:index, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end

    namespace :metasploit do
      namespace :credential do
        root to: 'cores#index'

        resources :cores do
          collection do
            delete :destroy_multiple
            get    :export
            get    :filter_values
            post   :quick_multi_tag
            get    :search_operators
          end

          member do
            put :remove_tag
            get :tags
          end

          resources :logins do
            collection do
              delete :destroy_multiple
              post :quick_multi_tag
            end

            member do
              post :get_session
              put :remove_tag
              get :tags
              post :validate_authentication
            end
          end

          resource  :origin, only: [:show]
        end

        resources :logins do
          member do
            post :attempt_session
            get  :get_session
            post :validate_authentication
          end
        end
      end
    end

    resources :module_details, only: [:show]

    namespace :nexpose do
      namespace :data do
        resources :import_runs, only: [:create,:show]

        resources :sites, only: [:index] do
          collection do
            get :filter_values
            get :search_operators
          end
        end
      end

      namespace :result do
        resources :exceptions, only: [:create,:show]
        resources :export_runs, only: [:create]

        # fixme: CHANGE TO POST TO PREVENT CSRF.
        get 'push_validations' => 'exceptions#push_validations'

        resources :validations, only: [:create,:show]
      end
    end

    note_or_service_collection_routes = ->{
      get :combined
      delete :destroy_multiple
      post :quick_multi_tag
    }

    resources :notes, only: [:create, :index] do
      collection(&note_or_service_collection_routes)
    end

    # Outside of reports to avoid dealing with report IDs unnecessarily:
    get 'report_artifact_download/(:id)', to: 'report_artifacts#download'
    get 'report_artifact_view/:id',       to: 'report_artifacts#view'

    # Resources for custom reports: logos, templates
    resources :report_custom_resources

    # Example simple template
    get 'report_template_simple_download',to: 'reports#download_simple_sample'

    # Reports and Exports
    # Standard reports
    resources :reports do
      collection do
        delete :destroy_multiple
        # Wrapper to allow all the other report partials
        # to be reloaded once type is selected:
        get :form_for_type
        post  "validate_report",
              as: "validate_report",
              action: :validate_report
      end

      member do
        get :clone
        post :format_generation_status
        post :generate_format
      end

      # Generated report files
      resources :report_artifacts, only: [:destroy, :index] do
        collection do
          post :email
        end

        member do
          get :download
          get :view
        end
      end
    end

    resources :run_stats, only: [:show]

    resources :services, only: [:index] do
      collection(&note_or_service_collection_routes)
    end

    resources :sessions, only: [:index]

    namespace :shared do
      resources :payload_settings, only: [:index, :create]
    end

    # NEW STYLE!
    # Social Engineering Campaigns
    namespace :social_engineering do
      resources :email_templates, except: [:delete]  do
        collection do
          delete "" => "email_templates#destroy", :as => "delete"
        end

        patch "edit" => "email_templates#update", on: :member
      end

      resources :files, except: [:delete]  do
        collection do
          delete "" => "files#destroy", :as => "delete"
        end
      end

      resources :human_targets, only: [:show]

      resources :target_lists, except: [:delete]  do
        collection do
          delete "" => "target_lists#destroy", :as => "delete"
        end

        get "export" => "target_lists#export"

        resources :human_targets, only: [:index] do
          collection do
            delete "" => "human_targets#destroy", :as => "delete"
          end
        end

      end

      resources :web_templates, except: [:delete] do
        collection do
          delete "" => "web_templates#destroy", :as => "delete"
          post :clone_proxy
        end
      end

      #
      # TODO ordered above, unordered below
      #

      # ------ Campaigns, components, and tracking data -----
      resources :campaigns do
        collection do
          delete "" => "campaigns#destroy", :as => "delete"
          get :logged_in
        end

        member do
          get  :check_for_configuration_errors
          post :execute
          get  :links_clicked
          get  :opened_emails
          get  :opened_sessions
          post :reset
          get  :sent_emails
          get  :submitted_forms
          get  :to_task
        end

        resource :email_server_config,
                 controller: :email_server_config,
                 only: [:edit, :update] do
          collection do
            match :check_smtp, via: [:put, :patch]
          end
        end

        resources :emails do
          collection do
            post :custom_content_preview
          end

          get :preview
          get :preview_pane
        end

        resources :phishing_results, :only => [:index, :show]

        resources :portable_files do
          member do
            get :download
          end
        end

        resources :visits

        resources :web_pages do
          collection do
            post :clone_proxy
            post :custom_content_preview
          end

          get :preview
          get :preview_pane
        end

        resource :web_server_config,
                 controller: :web_server_config,
                 only: [:edit, :update]

      end
    end

    namespace :sonar do
      resources :imports, only: [:index, :create] do
        #When we scope fdns results to an import run
        resources :fdnss, only: :index, controller: 'fdnss' do
          collection do
            get :filter_values

apps/pro/ui/app/controllers/exports_controller.rb
class ExportsController < ApplicationController

  before_action :load_workspace

  def index
    @exports = @workspace.exports
    respond_to do |format|
      format.html do
        render :action => "index", :layout => "application"
      end
      format.json do
        render :json => DataTableQueryResponse.build(params, {
          :collection => @exports,
          :search_cols => [:file_path, :created_by,
                           :state, :export_type],
          :columns => [:id, :file_path, :etype, :created_by, :state,
                       :created_at, :actions],
          :render_row => lambda { |export|
            { :file_path => File.basename(export.file_path), :etype => export.etype.pretty_name }
          }
        })
      end
    end
  end

  def new
    @export = Export.new(:export_type => :xml)
  end

  def create
    params[:export] ||= {}
    export_params = exports_params.merge(:workspace_id => @workspace.id)
    @export = Export.new(export_params)
    @export.created_by = current_user.username

    unless @export.save
      render :action => 'new',
             :locals => {:export => @export,
                         :error => @export.errors.full_messages.join('<br/>')
             },
             :status => :bad_request
      return
    end

    # Adds export generation process to DJ queue:
    @export.generate_delayed
    flash[:notice] = 'Export creation queued. Table will refresh shortly...'
    redirect_to workspace_exports_path(@workspace)
  end

  def download
    @export = Export.find(params[:id])
    export_filename = File.basename(@export.file_path)
    export_extension = File.extname(@export.file_path)[1..-1]

    file_types = {
        'xml'  => 'application/xml',
        'txt'  => 'text/plain',
        'zip'  => 'application/zip'
    }
    current_type = file_types[export_extension]

    file_data = File.open(@export.file_path, 'rb') { |f| f.read }
    # Prompt for file download:
    send_data(file_data,
              :type => current_type,
              :filename => export_filename)
  end

  def destroy
    @export.destroy
    flash[:notice] = "Deleted export #{@export.file_path}."
  end

  def destroy_multiple
    Export.where(id: params[:export_ids], workspace_id: @workspace.id).destroy_all

    respond_to do |format|
      format.any(:html, :js) do
        # TODO Not showing up
        flash.now[:notice] = "Deleted #{export_ids.size} exports."
        redirect_to workspace_exports_path(@workspace)
      end
      format.json {
        render :json => { success: true }
      }
    end
  end

  private

  def exports_params
    params.fetch(:export, {}).permit!
  end
end

apps/pro/ui/app/views/exports/_address_settings.html.erb
<% unless @export.export_type == :mm_segment %>
    <%= f.inputs 'Address Settings' do -%>
        <%= f.input :included_addresses,
                    :label        => 'Included addresses',
                    :as           => :text,
                    :required     => false,
                    :wrapper_html => {:id => 'export_included_addresses_input'}
        %>
        <%= f.input :excluded_addresses,
                    :label        => 'Excluded addresses',
                    :as           => :text,
                    :required     => false,
                    :wrapper_html => {:id => 'export_excluded_addresses_input'}
        %>
    <% end -%>

    <%= f.help_link 'included_addresses' do %>
        <h3>Included and Excluded Addresses</h3>
        <p>Specify <b>Included Addresses</b> and <b>Excluded Addresses</b> to configure the scope of the export, or leave blank to include all the hosts associated with this project. Hosts with addresses outside the allowable range(s) will not be included in the exported data. Entries may be specified as single addresses (192.168.1.1), dashed entries (192.168.1.1-192.168.1.100), wildcards (192.168.1.*), or using CIDR notation (192.168.1.0/29).</p>
    <% end %>
<% end %>

apps/pro/ui/app/views/exports/_export_name.html.erb
<%= f.inputs 'Name' do -%>
    <%= f.input :name,
                :required => true
    %>
<% end %>

<%= f.help_link 'name' do %>
    <h3>Export name</h3>
    <p>The name to use in creating the export file. The file extension is added automatically based on the selected export type, so only the base name needs to be specified (e.g. an XML export named 'Engagement1' will result in INSTALL_PATH/pro/exports/Engagement1.xml)</p>
<% end %>

apps/pro/ui/app/views/exports/_export_nav_bar.html.erb
<div id='export_nav_bar'>
	<div class='control-bar-items'>
		<span class='button any'><%= link_to 'Delete', destroy_multiple_workspace_exports_path(@workspace, :format => :json), :data => { :confirm => 'Delete selected exports?' }, :id => 'user-delete-submit' %></span>
		<div class='separator'></div>
		<span class='button'><%= link_to 'Export Data', new_workspace_export_path(@workspace), :class => :export_data %></span>
	</div>
</div>

apps/pro/ui/app/views/exports/_export_options.html.erb
<%= f.inputs 'Options' do -%>
    <%= f.input :mask_credentials,
                :as => :boolean %>

    <%= f.help_link 'mask_credentials' do %>
        <h3>Export Options</h3>
        <p>Mask credentials: select this option to obfuscate any display of credential values in the resultant export. Note that this will not be applied to existing artifacts included in some exports, e.g. existing reports that are exported in a Zip Workspace export.</p>
    <% end %>
<% end %>

apps/pro/ui/app/views/exports/_export_type.html.erb
<% @export_type_map = Export::EXPORT_TYPE_MAP %>
<% @export_types = @export_type_map.keys.sort %>
<% @export_types_collection = []
   @export_types.each do |key|
     @export_types_collection << [ @export_type_map[key].pretty_name, key ]
   end
%>

<%= f.inputs "Export Type" do %>
    <%= f.input :export_type,
                :collection => @export_types_collection,
                :as => 'select',
                :include_blank => false
    %>

    <%= f.help_link :export_type do %>
        <h3>Available Export Types</h3>
        <ul>
          <% @export_types.each do |export_type| %>
              <% etype = @export_type_map[export_type] %>
              <% help_line = "#{etype.pretty_name}: #{etype.description}" %>
              <%= content_tag(:li, help_line) %>
          <% end %>
        </ul>
    <% end %>

<% end %>

apps/pro/ui/app/views/exports/_export_wrapper_form.html.erb
<div class="one_col_no_sidebar">
  <%= semantic_form_for [@workspace, @export] do |f| %>
      <%= f.hidden_field :workspace_id %>
      <%= render :partial => 'exports/export_type',      :locals => {:f => f} %>
      <%= render :partial => 'exports/export_name',      :locals => {:f => f} %>
      <%= render :partial => 'exports/address_settings', :locals => {:f => f} %>
      <%= render :partial => 'exports/export_options',   :locals => {:f => f} %>
      <%= render :partial => 'exports/submit_button',    :locals => {:f => f} %>
  <% end %>
</div>

apps/pro/ui/app/views/exports/_saved_exports.html.erb
<% include_javascript 'moment.min' %>

<div id="saved_exports">
	<h1>Saved Exports</h1>

	<table id="exports" class="list sortable">
		<thead>
			<tr>
				<th class="checkbox"><%= check_box_tag "all_exports" %></th>
				<th>File</th>
                <th>Export Type</th>
                <th>Creator</th>
                <th>Status</th>
                <th>Create Date</th>
				<th>Actions</th>
			</tr>
		</thead>
	</table>
</div>

apps/pro/ui/app/views/exports/_submit_button.html.erb
<%= f.actions do %>
    <span class="btn">
		<%= f.submit "Export Data", :class => "new" %>
    </span>
<% end -%>

apps/pro/ui/app/views/exports/index.html.erb
<% title "Exports" %>
<% breadcrumb workspace_link, exports_link %>

<% include_view_javascript -%>

<%= form_tag do %>
  <%= render :partial => "export_nav_bar" %>
  <%= render :partial => "saved_exports" %>
<% end %>

apps/pro/ui/app/views/exports/new.html.erb
<% title h('New Export') %>
<% include_stylesheet('exports') %>

<% breadcrumb workspace_link, exports_link, link_to("New Export", "#") %>

<div id='export_container'>
  <%= render :partial => 'exports/export_wrapper_form' %>
</div>