apps/pro/ui/config/routes.rb
begin
  # Try Pro::Application first as it won't autoload, so if it doesn't raise a NameError, then this must be called
  # from pro/ui
  engine = Pro::Application
rescue NameError
  # Used in metasploit-pro-engine and metamodules specs
  engine = Metasploit::Pro::UI::Engine
end

#change
engine.routes.draw do
  # Admin area
  namespace :admin do |admin|
    resources :users do
      collection do
        post "delete" => "users#destroy", :as => "mass_delete"
      end
    end
  end

  # API Keys
  resources :api_keys do
    collection do
      delete "/destroy" => "api_keys#destroy", :as => "destroy"
    end

    member do
      post "/reveal" => "api_keys#reveal"
    end
  end

  resources :banner_messages
  post "/banner_messages/read" => "banner_messages#read"

  get "/campaign_files/:id" => "social_engineering/files#download"

  # Creds
  resources :creds do
    collection do
      delete :destroy_multiple
    end
  end

  # Events
  resources :events

  scope '/licenses', controller: :licenses do
    get '', action: :index,
            as: 'licenses'
    post 'register', action: :register,
                     as: 'register'
    post 'activate', action: :activate,
                     as: 'activate'
    match 'offline_activation', action: :offline_activation,
                                as: 'offline_activation',
                                via: [:get, :post]
  end

  scope "hosts/:id" do
    get "new_loot" => "loots#new", :as => "new_loot"
    match "add_loot" => "loots#add_loot", :as => "add_loot", via: [:get, :post]
    get "" => "hosts#show", :as => "host"
    patch "" => "hosts#update", :as => "update_host"
    post "" => "hosts#create_or_update_tag"
    delete "" => "hosts#remove_tag", :as => "remove_tag"
    get "edit" => "hosts#edit", :as => "edit_host"
    get "services" => "hosts#services", :as => "host_services"
    get "sessions" => "hosts#sessions", :as => "host_sessions"
    get "vulns" => "hosts#vulns", :as => "host_vulns_tab"
    get "web_vulns" => "hosts#web_vulns", :as => "host_web_vulns_tab"
    get "shares" => "hosts#shares", :as => "host_shares"
    get "loots" => "hosts#loots", :as => "host_loots"
    get "notes" => "hosts#notes", :as => "host_notes"
    get "creds" => "hosts#creds", :as => "host_creds"
    get "tags" => "hosts#tags", :as => "host_tags"
    get "attempts" => "hosts#attempts", :as => "host_attempts"
    get "details" => "hosts#details", :as => "host_details"
    get "exploits" => "hosts#exploits", :as => "host_exploits"
    get "show_alive_sessions" => "hosts#show_alive_sessions", :as => "show_alive_sessions"
    get "show_dead_sessions" => "hosts#show_dead_sessions", :as => "show_dead_sessions"
    get "show_services/json" => "hosts#show_services", dataTable:false
    get "show_services" => "hosts#show_services", :as => "show_services", dataTable:true
    get "show_history" => "hosts#show_history", :as => "show_history"
    get "show_notes" => "hosts#show_notes", :as =>"show_notes"
    patch   "update_service" => "hosts#update_service", :as => "update_service"
    delete "delete_service" => "hosts#delete_service", :as => "delete_service"
    get "show_captured_data" => "hosts#show_captured_data", :as => "show_captured_data"
    put    "update_cred" => "hosts#update_cred", :as => "update_cred"
    delete "delete_cred" => "hosts#delete_cred", :as => "delete_cred"
    post   "create_service" => "hosts#create_service", :as => "create_service"
    post   "create_cred" => "hosts#create_cred", :as => "create_cred"
    post "poll_presenter" => "hosts#poll_presenter", :as => "poll_presenter"
    get  "poll_presenter" => "hosts#poll_presenter"
  end

  # Vulns
  scope "/hosts/:host_id", :as => "host" do
    resources :vulns

    namespace :metasploit do
      namespace :credential do
        resources :cores do
          collection do
            get :accessing,   action: :index, host_origin: :accessing
            get :originating, action: :index, host_origin: :originating
          end
        end

        resources :logins do
          collection do
            get :accessing, action: :index, host_origin: :accessing
          end
        end

      end
    end
  end

  # Listeners
  resources :listeners
  scope "/listener" do
    post ":id/stop" => "listeners#stop", :as => "listener_stop"
    post ":id/start" => "listeners#start", :as => "listener_start"
    get "module_options" => "listeners#module_options", :as => "macro_module_options"
  end
  delete "listeners" => "listeners#destroy", :as => "delete_listeners"

  # Backups
  scope "/backups" do
    get "new" => "backups#new", :as => "new_backup"
    post "create" => "backups#create", :as => "create_backup"
    post "restore" => "backups#restore", :as => "restore_backup"
    get "poll" => "backups#restore_poll", :as => "restore_poll"
    get "restart" => "backups#restart", :as => "backup_restart"
    post "status" => "backups#status", :as => "backup_restart_status"
    get "download" => "backups#download", :as => "download_backup"
    get "add" => "backups#add", :as => "add_backup"
    post "upload" => "backups#upload", :as => "upload_backup"
  end
  delete "backups" => "backups#destroy", :as => "delete_backups"

  get "login" => "user_sessions#new", :as => "login"
  post "logout" => "user_sessions#destroy", :as => "logout"

  # Mdm::Loot
  get "loot/:id" => "loots#get", :as => "loot"

  # Macros
  resources :macros
  scope "/macro" do
    delete ":id/delete_action/:action_id" => "macros#delete_action", :as => "macro_delete_action"
    delete ":id/delete_action" => "macros#delete_action", :as => "macro_delete_actions"
    post ":id/add_action" => "macros#add_action", :as => "macro_add_action"
    match "module_options" => "macros#module_options", :as => "module_options", via: [:get, :post]
  end
  delete "macros" => "macros#destroy", :as => "delete_macros"

  # NeXpose Consoles
  resources :nexpose_consoles do
    collection do
      delete "/destroy" => "nexpose_consoles#destroy", :as => "destroy"
    end
  end

  # Notifications
  namespace :notifications do
    resources :messages do
      collection do
        post 'mark_read' => 'messages#mark_read', :as => 'mark_read'
        get 'poll' => 'messages#poll', :as => 'poll'
      end
    end
  end

  # Payload information
  resources :payloads do
    collection do
      get :encoders
      get :formats
    end
  end

  namespace :rest_api do
    namespace :v1 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets

        resources :campaigns do
          resources :web_pages
          resources :emails
          resources :email_openings
          resources :phishing_results
          resources :visits
        end
      end
    end
    namespace :v2 do
      get "/base/" => "base#index"

      namespace :social_engineering do
        resources :target_lists
        resources :human_targets
      end

      resources :workspaces, only: [:index, :show] do
        resources :campaigns, only: [:index, :show], controller: 'social_engineering/campaigns' do
          resources :web_pages, only: [:index, :show], controller: 'social_engineering/web_pages'
          resources :emails, only: [:index, :show], controller: 'social_engineering/emails'
          resources :email_openings, only: [:index, :show], controller: 'social_engineering/email_openings'
          resources :phishing_results, only: [:index, :show], controller: 'social_engineering/phishing_results'
          resources :visits, only: [:index, :show], controller: 'social_engineering/visits'
        end
        resources :hosts, only: [:index, :show] do
          resources :sessions, only: [:index, :show]
          resources :notes, only: [:index, :show]
          resources :services, only: [:index, :show] do
            resources :vulns, only: [:index, :show]
            resources :web_sites, only: [:index, :show] do
              resources :web_forms, only: [:index, :show]
              resources :web_pages, only: [:index, :show]
              resources :web_vulns, only: [:index, :show]
            end
          end
        end
      end
    end
  end

  # Sessions
  scope "sessions/:id" do
    delete "" => "sessions#destroy", :as => "delete_session"
    match "route" => "sessions#route", :as => "session_route", via: [:get, :post]
    get "vnc" => "sessions#vnc", :as => "session_vnc"
    match "shell" => "sessions#shell", :as => "session_shell", via: [:get, :post]
    get "files" => "sessions#files", :as => "session_files"
    get "search" => "sessions#search", :as => "session_search"
    post "upload" => "sessions#upload", :as => "session_upload"
    get "download" => "sessions#download", :as => "session_download"
    get "delete" => "sessions#delete", :as => "session_delete"
  end

  # Global Settings
  scope "/settings" do
    get "" => "settings#index", :as => "settings"
    patch "update_profile" => "settings#update_profile", :as => "update_profile"
    put "update_profile" => "settings#update_profile"
  end

  # Setup & Licenses
  scope "/setup" do
    get ""           => "licenses#setup", :as => "setup"
    get "request"    => "licenses#request_key", :as => "request_key"
    get "activation" => "licenses#activation", :as => "activation"
  end

  # Mdm::Tag Search
  get "tags" => "tags#search", :as => "search_tags"

  scope 'tasks', controller: :tasks do
    post 'stop', action: :stop,
                 as: 'stop_task'
    post 'stop_all', action: :stop_all,
                     as: 'stop_all_tasks'

    post ':workspace_id/stop', action: :stop_in_workspace,
                               as: 'stop_tasks_in_workspace'
    get 'replay/:id', action: :replay,
                      as: 'replay_task'

    scope ':id' do
      get 'logs',
          as: 'task_log',
          action: :logs
      post 'pause',
           as: 'pause_task',
           action: :pause
      post 'resume',
           as: 'resume_task',

apps/pro/ui/app/helpers/vulns_helper.rb
module VulnsHelper
	# Generate the markup for the Mdm::Vuln's row checkbox.
	#
	# vuln - The Mdm::Vuln to fetch the attribute from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_host_checkbox_tag(vuln, opts={})
		markup = ""
		unless opts[:no_host]
			markup += check_box_tag("host_ids[]", vuln.host.id, false, :id => nil, :class => 'hosts')
		end
		class_name = if opts[:no_host] then '' else 'invisible' end
		markup += check_box_tag("vuln_ids[]", vuln.id, false, :id => nil, :class => "#{class_name} vulns")
		markup += "<div class='invisible'>"
		unless opts[:no_host]
			vuln.host.tags.each do |tag|
				markup += tag_html(tag)
			end
		end
		markup += "</div>"
		markup.to_json.html_safe
	end

	# Output the markup to display a ref's name as either a text field or a
	# plaintext, depending upon whether it appears on the new or edit views.
	#
	# ref  - The Mdm::Ref being displayed.
	# form - The FormBuilder instance for the Mdm::Ref's form.
	#
	# Returns the String markup.
	def ref_name_field(ref = nil, form = nil)
		if controller.action_name == 'edit'
			ref.name
		else
			form.text_field :name
		end
	end

	# Generate the markup for the Mdm::Vuln's Mdm::Host's name.
	#
	# vuln - The Mdm::Vuln to fetch the Mdm::Host's attribute from.
	#
	# Returns the String markup html, escaped for json.
	# TODO: Abstract this. It's used in several of the Analysis tab views.
	def vuln_host_name_html(vuln)
		raw_name = vuln.host.name
		# if the hostname was populated from a wildcard cert, we don't want
		#   to see a huge list of e.g. *.metasploit.com
		name_is_safe = raw_name.present? && !raw_name.starts_with?("*")
		name = name_is_safe ? (json_data_scrub(raw_name)) : vuln.host.address
		link_to(name, vuln.host).to_json.html_safe
	end

	# Generate the markup for the Mdm::Vuln name.
	#
	# vuln - The Mdm::Vuln to fetch the attribute from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_name_html(vuln)
		name = h(json_data_scrub(vuln.name))
		link_to(name, workspace_vuln_path(@workspace, vuln)).to_json.html_safe
	end

	# Calculate the status of an Mdm::Vuln
	#
	# TODO: Performance of this is terrible. See MSP-13179
	def vuln_status_html(vuln, params, opts={escape: true})

		latest_match_result = Mdm::ExploitAttempt.where({vuln_id:vuln.id}).last

		status_type =
			case latest_match_result.try(:exploited)
				when nil
					:not_tested
				when true
					:exploited
				when false
					:exploit_attempted
				else
					:not_tested
			end

    last_vuln_attempt = vuln.vuln_attempts.last

    if !last_vuln_attempt.nil? && !last_vuln_attempt.last_fail_reason.nil?
			status_type = :not_exploitable
    end

    if !last_vuln_attempt.nil?  && last_vuln_attempt.last_fail_reason.nil? && last_vuln_attempt.exploited == false
			status_type = :exploit_attempted
		end

		status = vuln_status_html_template(status_type)

    if opts[:escape]
      status.to_json.html_safe
    else
      status
    end
	end

	def vuln_status_html_template(status)
		case status
			when :not_tested
				css_class       = 'not-tested'
				css_data_status = 'not_exploitable'
				status_text     = 'Not Tested'
			when :exploited
				css_class       = 'exploited'
				css_data_status = 'exploited'
				status_text     = 'Exploited'
			when :exploit_attempted
				css_class       = 'exploit-attempted'
				css_data_status = 'not_exploitable'
				status_text     = 'Exploit Attempted'
			when :not_exploitable
				css_class       = 'not-exploitable'
				css_data_status = 'not_exploited'
				status_text     = 'Not Exploitable'
		end
		<<-TEMPLATE
		<div class='pill'>
		  <div class='#{css_class}' data-status='#{css_data_status}'>
				#{status_text}
			</div>
		</div>
    TEMPLATE
	end


	# Generate the markup for the Mdm::Vuln's refs.
	#
	# vuln - The Mdm::Vuln to fetch the relationship from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_refs_html(vuln)
		refs = vuln.refs
		pref = [ "CVE", "OSVDB", "BID", "NEXPOSE" ]

		tbl = ""
		ref = nil
		pref.each do |rt|
			ref = refs.select{|r| r.name.index(rt+"-") == 0 }.first
			break if ref
		end

		ref ||= refs.first

		if ref
			ref_link = link_for_ref(*ref.link_info)

			tbl = "<div class='full-ref-map invisible'>"
			tbl += "<h2>#{h vuln.name}</h2><br/>"
			tbl += ref_map(refs, 3)
			tbl += "</div>"

			tbl << '<table width="100%">'
			tbl << "<tr><td>"
			tbl << ref_link

			if refs.length > 1
				tbl << " ("
				tbl << link_to("#{refs.length} Total", '', :class => 'full-ref-map-view')
				tbl << " )"
			end

			tbl << "</td></tr>"
			tbl << "</table>"
		else
			tbl = '<table width="100%"><tr><td>No references</td></tr></table>'
		end
		return tbl.to_json.html_safe
	end


	# Generate the markup for the Mdm::Vuln's attempt counter
	#
	# vuln - The Mdm::Vuln to fetch the relationship from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_attempts_html(vuln)
		(
			case vuln.vuln_attempt_count
			when 0
				"&nbsp;"
			when 1
				"<img src='/assets/icons/silky/tick.png' title='Tested Once'>"
			else
				"<img src='/assets/icons/silky/tick.png' title='Tested #{vuln.vuln_attempt_count} Times'>"
			end
		).to_json.html_safe
	end

	# Generate the markup for the Mdm::Vuln's exploit counter
	#
	# vuln - The Mdm::Vuln to fetch the relationship from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_exploits_html(vuln)

		res = '&nbsp;'

		if vuln.exploited_at
			res = "<img src='/assets/icons/silky/exclamation.png' title='Exploited at #{vuln.exploited_at.to_s}'>"
		elsif vuln.vuln_attempt_count == 1
			res = "<img src='/assets/icons/silky/tick.png' title='Tested once'>"
		elsif vuln.vuln_attempt_count > 1
			res = "<img src='/assets/icons/silky/tick.png' title='Tested #{vuln.vuln_attempt_count} times'>"
		else
			res = "<img src='/assets/icons/silky/bullet_white.png' title='Untested'>"
		end

		res.to_s.to_json.html_safe
	end


	# Generate the markup for the Mdm::Vuln's exploit counter
	#
	# vuln - The Mdm::Vuln to fetch the relationship from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_service_html(vuln)
		( vuln.service ? "#{vuln.service.port}/#{vuln.service.proto}" : "&nbsp;" ).to_json.html_safe
	end

	# Generate the markup for the Mdm::Vuln's refs count.
	#
	# vuln - The Mdm::Vuln to fetch the relationship from.
	#
	# Returns the String markup html, escaped for json.
	def vuln_host_count_html(vuln)
		link_to(vuln.host_count, workspace_vulns_path(@workspace, :search => vuln.name)).to_json.html_safe
	end
end

apps/pro/ui/app/views/vulns/_form.html.erb
<%= render "shared/error_messages", :target => @vuln %>

<%= f.inputs "Vulnerability Details" do -%>
	<%= f.input :name, :required => true, :input_html => { :size => 50 } %>
	<%= f.input :info, :required => false, :label => "Information", :input_html => { :size => 50 } %>
<% end -%>


<%= f.inputs "References" do -%>
	<div class='control-bar'>
		<span class='button'><%= link_to "Add Reference", '#', :class => "new", :id => 'add-reference' %></span>
	</div>

	<table class="list" id="references" style="width: 100%;">
		<thead>
			<tr>
				<th>Name</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @vuln.refs.each do |ref| -%>
			<% new_or_existing = ref.new_record? ? 'new' : 'existing' %>
			<% prefix = h "#{new_or_existing}_ref_attributes[]" %>

				<%= f.fields_for prefix, ref do |reference| %>
					<tr class="fields">
						<td><%= reference.text_field :name, :size => 60 %></td>
						<td class='delete'><%= link_to(icon('delete'), '#', :title => 'Delete Reference' ) %></td>
					</tr>
				<% end %>
			<% end -%>
		</tbody>
	</table>
<% end -%>

apps/pro/ui/app/views/vulns/_vuln_attempts.html.erb
<table class="sortable list" id="attempts-table">
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Exploit</th>
      <th>Result</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% reset_cycle "rows" %>
  <% @vuln.vuln_attempts.each do |att| %>
    <tr>
      <td><%= att.module.to_s %></td>
      <td><%= att.username.to_s %></td>
      <td><%= att.exploited ? "Exploited" : "Failed: #{att.fail_reason}" %></td>
      <td width="30">
        <%= att.attempted_at.to_s %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

apps/pro/ui/app/views/vulns/_vuln_attempts_tab.html.erb
<% content_for :head do %>
  <meta name="msp:module_run_path" content="<%= new_module_run_path(@workspace.id, '') %>" />
<% end %>

<%= form_tag '',  :method => "POST", :id => 'new_module_run' do |f| %>
<%= hidden_field_tag 'host_ids[]', @vuln.host.id, :id => "host_ids_#{@vuln.host.id}_module" %>
<% end %>

<table class="sortable list" id="vuln-attempts-tbl">
	<thead>
		<tr>
			<th>Time</th>
			<th>User</th>
			<th>Exploit</th>
			<th>Result</th>
			<th>Detail</th>
		</tr>
	</thead>
	<tbody>
	<% reset_cycle "rows" %>
	<% @vuln.vuln_attempts.each do |att| %>
		<tr class="<%=h row_cycle %>">
			<td width="140">
				<%= att.attempted_at.strftime('%Y-%m-%d %H:%M:%S %z').to_s %>
			</td>
			<td><%= att.username.to_s %></td>
			<td><%= link_to h(att.module), "#", :class => "module-name", :module_fullname => att.module %></td>
			<td><%=
					att.exploited ? 
					( att.session_id ? 
						link_to("Exploited", session_history_path(@workspace, att.session_id)) :
						"Exploited"
					) : 
					"#{att.fail_reason.to_s.upcase}" 
			%></td>
			<td><%= truncate(att.fail_detail.to_s, :length => 60) %></td>
		</tr>
	<% end %>
	</tbody>
</table>

apps/pro/ui/app/views/vulns/_vuln_details_tab.html.erb
<% @vuln.vuln_details.each do |vd| %>


<div class='details_header'>
<h2>
	<%= vd.src.upcase %> -
	<%= vd.title %>
	<% if vd.cvss_score %>
		( CVSS <%= vd.cvss_score %> )
	<% end %>
</h2>
</div>

<table class='details'>

<tr>
	<td class='field'>
		Proof
	</td>
</tr>
<tr>
	<td class='value'>
		<pre class='verbose'><%= vd.proof%></pre>
	</td>
</tr>


<% if vd.src == "nexpose" %>

<tr>
	<td class='field'>
		Nexpose Data
	</td>
</tr>
<tr>
	<td class='value'>

<table class='nexpose_details'>

<%
	nx_fields = %W{ 
		nx_vuln_status nx_vulnerable_since nx_proof_key
		nx_severity nx_pci_severity nx_pci_compliance
		nx_tags
		nx_added nx_published nx_modified 
		nx_console_id nx_device_id nx_scan_id
	}


nx_fields.each do |k|
	next unless vd[k]

	kn = k.gsub(/^nx_/, '').split('_').map{|x| x.capitalize }.join(" ").gsub('Id', 'ID').gsub('Pci', 'PCI')
%>
<tr>
	<td class='nexpose_field'>
		<%= kn %>
	</td>
	<td class='nexpose_value'>
		<%= vd[k] %>
	</td>
</tr>
<% end %>

</table>

	</td>
</tr>

<% end %>

<tr>
	<td class='field'>Description</td>
</tr>
<tr>
	<td class='value'>
		<pre class='verbose'><%= vd.description%></pre>
	</td>
</tr>

<tr>
	<td class='field'>Solution</td>
</tr>
<tr>
	<td class='value'>
		<pre class='verbose'><%= vd.solution%></pre>
	</td>
</tr>

</table>

<% end %>

apps/pro/ui/app/views/vulns/_vulns.html.erb
<span id="vulns-path" class="invisible"><%= workspace_vulns_path(@workspace, :format => :json, :search => params[:search]) %></span>

    <span style="<%= if @automatic_exploitation_runs.count <= 1 then "visibility:hidden;" else ""  end %>">
      <%= label_tag :exploitation_run, 'Exploitation Run' %>
      <%= select_tag(:exploitation_run,options_from_collection_for_select(@automatic_exploitation_runs, 'id',:updated_at))  %>
    </span>

		<% if @automatic_exploitation_runs.count > 0 %>
      <% if License.get.supports_vuln_validation? %>
        <div class="btns">
          <div class="create-exception">
            <span class="btn"><%= link_to "Push Exploited Vulnerabilities", "javascript:void(0)" ,:class => :nexpose %></span>
          </div>
          <div class="create-exception dropdown">
            <div class="dropdown-list">
              <ul>
                <li class="non-exploited">All Not Exploited</li>
                <li class="all">All Selected</li>
              </ul>
            </div>
                <span class="btn">
                  <%= link_to "Create Exception", "javascript:void(0)", :class=> :dropdown %>
                </span>
            <div class="arrow">
                  <span class="btn">
                    <%= link_to "&#9660;".html_safe, "javascript:void(0)", :class=> :dropdown %>
                  </span>
            </div>
          </div>
        </div>
      <% else %>
        <div class="buttons" style="text-align: right;">
        <span class="btn">
          <%= submit_checkboxes_to "Nexpose Exceptions", new_nexpose_exception_push_path(@workspace), { :class => "nexpose" } %>
        </span>
        </div>
      <% end %>
		<% end %>

<% if License.get.supports_vuln_validation? %>
  <table id="vulns-table" class="list sortable vuln-validation">
<% else %>
  <table id="vulns-table" class="list sortable">
<% end %>
	<thead>
		<tr>
			<th class="checkbox"><%= check_box_tag "all_vulns", false %></th>
			<th>Host</th>
			<th>Service</th>
			<th>Name</th>
      <% if License.get.supports_vuln_validation? %>
			  <th>Nexpose Test Status</th>
      <% else %>
        <th><%= image_tag('icons/silky/shield.png', title: 'Defended') %></th>
      <% end %>
			<th>References</th>
		</tr>
	</thead>
	<tbody id="vuln_list">
	</tbody>
</table>

apps/pro/ui/app/views/vulns/_vulns.json.erb
{ 
  "sEcho": <%= echo_data_tables %>,
  "iTotalRecords": <%= @vulns_total_count.to_json %>,
  "iTotalDisplayRecords": <%= @vulns_total_display_count.to_json %>,
  "aaData": [
  <% @vulns.each_with_index do |vuln, index| -%>
    {
      "DT_RowId":   <%= dom_id(vuln).to_json.html_safe %>,
      "checkbox":   <%= vuln_host_checkbox_tag(vuln) %>,
      "host":       <%= vuln_host_name_html(vuln) %>,
      "service":    <%= vuln_service_html(vuln) %>,		
      "name":       <%= vuln_name_html(vuln) %>,

      <% if License.get.supports_vuln_validation? %>
        "status":   <%= vuln_status_html(vuln, params) %>,
      <% else %>
        "exploits": <%= vuln_exploits_html(vuln) %>,
      <% end %>

    "refs":       <%= vuln_refs_html(vuln) %>
    }<%= ',' unless index == (@vulns.size - 1) %>
  <% end -%>
  ]
}

apps/pro/ui/app/views/vulns/_vulns_combined.html.erb
<span id="vulns-combined-path" class="invisible"><%= combined_workspace_vulns_path(@workspace, :format => :json) %></span>

<table id="vulns-table" class="list sortable">
	<thead>
		<tr>
      <th class="checkbox"><%= check_box_tag "all_vulns", false %></th>
			<th>Name</th>
			<th>References</th>
			<th>Hosts</th>
		</tr>
	</thead>
	<tbody id="vuln_list">
	</tbody>
</table>

apps/pro/ui/app/views/vulns/_vulns_combined.json.erb
{ 
  "sEcho": <%= echo_data_tables %>,
  "iTotalRecords": <%= @vulns_total_count.to_json %>,
  "iTotalDisplayRecords": <%= @vulns_total_display_count.to_json %>,
  "aaData": [
  <% @vulns.each_with_index do |vuln, index| -%>
  	<% latest_vuln = @vulns.first -%>
    {
      "checkbox":   <%= vuln_host_checkbox_tag(vuln, :no_host => true) %>,
      "name":       <%= vuln_name_html(vuln) %>,
      "refs":       <%= vuln_refs_html(latest_vuln) %>,
      "host_count": <%= vuln_host_count_html(vuln) %>
    }<%= ',' unless index == (@vulns.size - 1) %>
  <% end -%>
  ]
}

apps/pro/ui/app/views/vulns/combined.html.erb
<% title "Disclosed Vulnerabilities" %>
<% breadcrumb workspace_link, vulns_link %>


<% include_javascript "jquery.watch" -%>
<% include_javascript "dataTables.filteringDelay" -%>
<% include_view_javascript -%>


<%= form_tag url: destroy_multiple_groups_workspace_vulns_path(@workspace), method: :post, html: {:id => 'table-form', :class => 'vulns_combined'}, remote: true do %>
  <%= render :partial => 'shared/analysis_tabs' %>
    <div class='tab_panel'>
    <div class="control-bar-items">
      <span class="button"><%= link_to "Individual View", workspace_vulns_path(@workspace), :class => 'multiple' %></span>
      <span class="button any"><%= submit_delete(destroy_multiple_groups_workspace_vulns_path(@workspace), 'Delete ALL vulns in the selected groups?') %></span>
    </div>
    <div id="vulns-table-wrapper">
      <%= render :partial => "vulns_combined" %>
    </div>
  </div>
<% end %>

apps/pro/ui/app/views/vulns/destroy.js.erb
jQuery("#<%= dom_id(@vuln) %>").fadeOut();